### ISSUE TITLE
Stuck on no patches found 

### ISSUE THREAD

**Issue by omar909** [leycec/fsnrnue#36]
![image](https://github.com/user-attachments/assets/6bd457bc-51e5-4719-8400-ccafadbe426e)
At first I got this message. after installing the patch from mediafire link and adding it to the folder and choosing the folders. The game won't run and I got this message. I also tried using both the offline and online installer.

The file /home/shrimp/Games/fate-stay-night-realta-nua-ultimate-edition/drive_c/Program Files/Fate／stay night[Realta Nua] Ultimate Edition/Fate64.exe could not be found

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 668, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 607, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1202, in play
    raise MissingGameExecutableError(filename=game_exe)

lutris.exceptions.MissingGameExecutableError: The file /home/shrimp/Games/fate-stay-night-realta-nua-ultimate-edition/drive_c/Program Files/Fate／stay night[Realta Nua] Ultimate Edition/Fate64.exe could not be found

What can I do

**Comment by Valnir17** [comment]
I fixed that issue by dropping the patches onto the folder manually

**Comment by Carl-Nguyen-02** [comment]
> I fixed that issue by dropping the patches onto the folder manually

Where did you find the patches? I clicked on the link to mega, and the content has already been removed?

**Comment by TDCMC** [comment]
Please refer to https://github.com/leycec/fsnrnue/issues/37#issuecomment-2606470976

**Comment by PhoenixCausesOof** [comment]
The creator of the https://forums.nrvnqsr.com/showthread.php/9101-Fate-Stay-Night-Realta-Nua-Ultimate-Edition-2022 thread updates the patches and comments the new Mega links accordingly. You just need to open to the latest pages and go back until you find them. Look for the "Last" button on the bottom right corner, after scrolling down the page.

I also had two problems regarding the install script:
1. It did not extract "Heaven's Feel.7z". I did it manually and moved and the files in the extracted folder to the respective one in "Program Files".
2. It installed the "Fate／stay night[Realta Nua] Ultimate Edition" folder to "Program Files (x86)" instead of just "Program Files", which can be easily fixed.

Hope this helps.

P.S. since Mega has "transfer quota"/download limits I ended up resorting to Nyaa (Sukebei) to get the patch files that were too big.
